# -*- coding: utf-8 -*-
"""stock_recommendation_WITH_REFRESH.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P26_Vsyc1AmpIkRBeNxWjBzJaBEpvs7t
"""

"""
🤖 국내 주식 AI 추천 시스템 v3.1 - 최종 완성판
- 전체 2,700개 종목 분석
- 평일 오전 8시 자동 업데이트
- 수동 새로고침 기능 (GitHub Actions 트리거)
"""

from datetime import datetime, timedelta
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

print("🔧 필요한 라이브러리 확인 중...")

try:
    import FinanceDataReader as fdr
    from pykrx import stock
    print("✅ 라이브러리 로드 완료")
except ImportError:
    print("📥 라이브러리 설치 중...")
    import subprocess
    subprocess.run(["pip", "install", "-q", "finance-datareader", "pykrx"], check=False)
    import FinanceDataReader as fdr
    from pykrx import stock
    print("✅ 라이브러리 설치 및 로드 완료")

import time

# ========================================
# 📊 설정
# ========================================

SYSTEM_TITLE = "국내 주식 AI 추천 시스템 (전체 종목 분석)"
MAX_STOCKS_TO_SCAN = 999999  # 전체 종목 스캔 (무제한)
MIN_PRICE = 1000
TOP_N_STOCKS = 8
MAX_RSI = 40

# GitHub 설정 (사용자가 설정해야 함)
GITHUB_USERNAME = "jediydc-cloud"  # 예: "john-doe"
GITHUB_REPO = "stock-recommendation"  # 예: "stock-recommendation"
GITHUB_TOKEN = "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"  # 나중에 설명

# ========================================
# 📈 데이터 수집 클래스 (동일)
# ========================================

class StockAnalyzer:
    """실시간 주식 분석기"""

    def __init__(self):
        self.today = datetime.now()
        self.today_str = self.today.strftime('%Y%m%d')
        print(f"\n📅 분석 기준일: {self.today.strftime('%Y년 %m월 %d일')}")

    def get_all_stocks(self):
        """전체 상장 종목"""
        try:
            kospi = fdr.StockListing('KOSPI')
            kosdaq = fdr.StockListing('KOSDAQ')
            all_stocks = pd.concat([kospi, kosdaq], ignore_index=True)

            if 'Market' not in all_stocks.columns:
                all_stocks['Market'] = all_stocks['Code'].apply(
                    lambda x: 'KOSPI' if x in kospi['Code'].values else 'KOSDAQ'
                )
            if 'Sector' not in all_stocks.columns:
                all_stocks['Sector'] = '기타'

            return all_stocks
        except:
            return None

    def calculate_rsi(self, prices, period=14):
        """RSI 계산"""
        try:
            delta = prices.diff()
            gain = (delta.where(delta > 0, 0)).rolling(window=period).mean()
            loss = (-delta.where(delta < 0, 0)).rolling(window=period).mean()
            rs = gain / loss
            rsi = 100 - (100 / (1 + rs))
            return rsi.iloc[-1]
        except:
            return None

    def get_stock_data(self, code, name):
        """개별 종목 데이터"""
        try:
            end_date = self.today
            start_date = end_date - timedelta(days=90)
            df = fdr.DataReader(code, start_date, end_date)

            if df is None or len(df) < 20:
                return None

            current_price = df['Close'].iloc[-1]
            prev_close = df['Close'].iloc[-2] if len(df) > 1 else current_price
            change_pct = ((current_price - prev_close) / prev_close) * 100

            rsi = self.calculate_rsi(df['Close'])
            if rsi is None or rsi > MAX_RSI:
                return None

            ma5 = df['Close'].rolling(window=5).mean().iloc[-1]
            ma20 = df['Close'].rolling(window=20).mean().iloc[-1]
            disparity_20 = (current_price / ma20) * 100

            avg_volume = df['Volume'].tail(20).mean()
            current_volume = df['Volume'].iloc[-1]
            volume_ratio = (current_volume / avg_volume) * 100 if avg_volume > 0 else 0

            typical_price = (df['High'].iloc[-1] + df['Low'].iloc[-1] + df['Close'].iloc[-1]) / 3
            vwap = typical_price
            vwap_diff = ((current_price - vwap) / vwap) * 100

            golden_cross = ma5 > ma20 and df['Close'].rolling(5).mean().iloc[-2] <= df['Close'].rolling(20).mean().iloc[-2]

            return {
                'code': code,
                'name': name,
                'current_price': int(current_price),
                'change_pct': round(change_pct, 2),
                'rsi': round(rsi, 1),
                'disparity_20': round(disparity_20, 1),
                'volume_ratio': round(volume_ratio, 1),
                'vwap_diff': round(vwap_diff, 2),
                'ma5': int(ma5),
                'ma20': int(ma20),
                'golden_cross': golden_cross
            }
        except:
            return None

    def get_fundamental_data(self, code):
        """재무 데이터"""
        try:
            df = stock.get_market_fundamental(self.today_str, self.today_str, code)
            if df.empty:
                return None

            per = df['PER'].iloc[0]
            pbr = df['PBR'].iloc[0]

            return {
                'per': round(per, 2) if per > 0 else 0,
                'pbr': round(pbr, 2) if pbr > 0 else 0
            }
        except:
            return None

    def calculate_risk_level(self, tech_data, fund_data):
        """위험도 계산"""
        risk_score = 0

        if tech_data['rsi'] < 20:
            risk_score += 1
        elif tech_data['rsi'] < 30:
            risk_score += 2
        else:
            risk_score += 3

        if tech_data['volume_ratio'] > 200:
            risk_score += 1
        elif tech_data['volume_ratio'] > 150:
            risk_score += 2
        else:
            risk_score += 3

        if fund_data and fund_data['pbr'] > 0:
            if fund_data['pbr'] < 0.3:
                risk_score += 1
            elif fund_data['pbr'] < 0.5:
                risk_score += 2
            else:
                risk_score += 3
        else:
            risk_score += 2

        avg_risk = risk_score / 3
        if avg_risk <= 1.5:
            return "저"
        elif avg_risk <= 2.5:
            return "중"
        else:
            return "고"

    def calculate_score(self, tech_data, fund_data):
        """점수 계산"""
        score = 0
        reasons = []

        if tech_data['rsi'] < 25:
            score += 30
            reasons.append(f"RSI {tech_data['rsi']} 극심한 과매도")
        elif tech_data['rsi'] < 30:
            score += 25
            reasons.append(f"RSI {tech_data['rsi']} 과매도")
        elif tech_data['rsi'] < 35:
            score += 15
            reasons.append(f"RSI {tech_data['rsi']} 과매도 진입")

        if tech_data['disparity_20'] < 90:
            score += 20
            reasons.append(f"20일선 이격도 {tech_data['disparity_20']}%")
        elif tech_data['disparity_20'] < 95:
            score += 15
            reasons.append(f"이격도 {tech_data['disparity_20']}%")

        if tech_data['volume_ratio'] > 200:
            score += 20
            reasons.append(f"거래량 {int(tech_data['volume_ratio'])}% 급증")
        elif tech_data['volume_ratio'] > 150:
            score += 15
            reasons.append(f"거래량 증가 {int(tech_data['volume_ratio'])}%")

        if -5 < tech_data['vwap_diff'] < 0:
            score += 15
            reasons.append("VWAP 지지선 근접")

        if fund_data and fund_data['pbr'] > 0:
            if fund_data['pbr'] < 0.3:
                score += 15
                reasons.append(f"PBR {fund_data['pbr']}배 극저평가")
            elif fund_data['pbr'] < 0.5:
                score += 12
                reasons.append(f"PBR {fund_data['pbr']}배 저평가")

        return score, reasons

    def scan_stocks(self):
        """전체 종목 스캔"""
        print("\n" + "="*70)
        print("🔍 실시간 종목 스캔 시작")
        print("="*70)

        all_stocks = self.get_all_stocks()
        if all_stocks is None:
            return [], [], [], {}

        print(f"✅ 총 {len(all_stocks)}개 종목 수집")

        candidates = []
        golden_cross_stocks = []
        high_volume_stocks = []
        sector_analysis = {}

        scan_count = 0
        max_scan = min(MAX_STOCKS_TO_SCAN, len(all_stocks))

        print(f"📊 {max_scan}개 종목 분석 중...\n")
        start_time = time.time()

        for idx, row in all_stocks.iterrows():
            if scan_count >= max_scan:
                break

            code = row['Code']
            name = row['Name']
            sector = row.get('Sector', '기타')

            if scan_count % 50 == 0 and scan_count > 0:
                elapsed = time.time() - start_time
                speed = scan_count / elapsed
                remaining = (max_scan - scan_count) / speed if speed > 0 else 0
                print(f"📈 진행: {scan_count}/{max_scan} ({scan_count/max_scan*100:.0f}%) | "
                      f"후보: {len(candidates)}개 | 예상: {int(remaining)}초")

            scan_count += 1

            tech_data = self.get_stock_data(code, name)
            if tech_data is None:
                continue

            if tech_data['current_price'] < MIN_PRICE:
                continue

            fund_data = self.get_fundamental_data(code)
            score, reasons = self.calculate_score(tech_data, fund_data)

            if sector not in sector_analysis:
                sector_analysis[sector] = {'count': 0, 'avg_rsi': [], 'rising': 0}
            sector_analysis[sector]['count'] += 1
            sector_analysis[sector]['avg_rsi'].append(tech_data['rsi'])
            if tech_data['change_pct'] > 0:
                sector_analysis[sector]['rising'] += 1

            if tech_data.get('golden_cross'):
                golden_cross_stocks.append({
                    'name': name,
                    'code': code,
                    'price': tech_data['current_price'],
                    'change': tech_data['change_pct']
                })

            if tech_data['volume_ratio'] > 200:
                high_volume_stocks.append({
                    'name': name,
                    'code': code,
                    'volume_ratio': tech_data['volume_ratio'],
                    'price': tech_data['current_price']
                })

            if score < 30:
                continue

            risk_level = self.calculate_risk_level(tech_data, fund_data)

            candidates.append({
                'score': score,
                'tech': tech_data,
                'fund': fund_data,
                'reasons': reasons,
                'sector': sector,
                'market': row.get('Market', '알수없음'),
                'risk_level': risk_level
            })

            time.sleep(0.05)

        elapsed = time.time() - start_time
        print(f"\n✅ 스캔 완료: {scan_count}개 분석 ({int(elapsed)}초)")
        print(f"   - 추천 후보: {len(candidates)}개")
        print(f"   - 골든크로스: {len(golden_cross_stocks)}개")
        print(f"   - 거래량 급증: {len(high_volume_stocks)}개")

        candidates.sort(key=lambda x: x['score'], reverse=True)
        golden_cross_stocks.sort(key=lambda x: x['change'], reverse=True)
        high_volume_stocks.sort(key=lambda x: x['volume_ratio'], reverse=True)

        return candidates[:TOP_N_STOCKS], golden_cross_stocks[:10], high_volume_stocks[:10], sector_analysis


def get_market_overview():
    """시장 개요"""
    try:
        kospi_df = fdr.DataReader('KS11', datetime.now() - timedelta(days=30), datetime.now())
        kosdaq_df = fdr.DataReader('KQ11', datetime.now() - timedelta(days=30), datetime.now())

        kospi_value = kospi_df['Close'].iloc[-1]
        kospi_prev = kospi_df['Close'].iloc[-2]
        kospi_change = ((kospi_value - kospi_prev) / kospi_prev) * 100

        kosdaq_value = kosdaq_df['Close'].iloc[-1]
        kosdaq_prev = kosdaq_df['Close'].iloc[-2]
        kosdaq_change = ((kosdaq_value - kosdaq_prev) / kosdaq_prev) * 100

        def calc_rsi(prices):
            delta = prices.diff()
            gain = (delta.where(delta > 0, 0)).rolling(window=14).mean()
            loss = (-delta.where(delta < 0, 0)).rolling(window=14).mean()
            rs = gain / loss
            return 100 - (100 / (1 + rs)).iloc[-1]

        kospi_rsi = calc_rsi(kospi_df['Close'])
        kosdaq_rsi = calc_rsi(kosdaq_df['Close'])

        if kospi_rsi < 30:
            sentiment = "조정 국면 (반등 기회)"
        elif kospi_rsi < 40:
            sentiment = "약세장 (저점 접근)"
        else:
            sentiment = "중립"

        return {
            'kospi': {'value': round(kospi_value, 2), 'change': round(kospi_change, 2), 'rsi': round(kospi_rsi, 1)},
            'kosdaq': {'value': round(kosdaq_value, 2), 'change': round(kosdaq_change, 2), 'rsi': round(kosdaq_rsi, 1)},
            'sentiment': sentiment
        }
    except:
        return {
            'kospi': {'value': 0, 'change': 0, 'rsi': 50},
            'kosdaq': {'value': 0, 'change': 0, 'rsi': 50},
            'sentiment': '분석 중'
        }


def generate_html(top8, golden_cross, high_volume, sector_analysis, market_data):
    """HTML 생성 - 새로고침 버튼 포함"""

    update_time = datetime.now().strftime('%Y년 %m월 %d일 %H:%M')
    weekday = datetime.now().strftime('%A')
    weekday_kr = {'Monday': '월', 'Tuesday': '화', 'Wednesday': '수',
                  'Thursday': '목', 'Friday': '금', 'Saturday': '토', 'Sunday': '일'}

    # 업종 분석 HTML
    sector_html = ""
    sorted_sectors = sorted(
        [(k, v) for k, v in sector_analysis.items() if v['count'] > 0],
        key=lambda x: sum(x[1]['avg_rsi']) / len(x[1]['avg_rsi']) if x[1]['avg_rsi'] else 50
    )[:5]

    for sector, data in sorted_sectors:
        avg_rsi = sum(data['avg_rsi']) / len(data['avg_rsi']) if data['avg_rsi'] else 50
        rising_pct = (data['rising'] / data['count'] * 100) if data['count'] > 0 else 0
        status = "🔴 약세" if avg_rsi < 35 else "🟢 강세" if avg_rsi > 60 else "⚪ 중립"

        sector_html += f"""
            <div class="sector-item">
                <div class="sector-name">{sector}</div>
                <div class="sector-info">
                    <span>RSI: {avg_rsi:.1f}</span>
                    <span>{status}</span>
                    <span>상승: {rising_pct:.0f}%</span>
                </div>
            </div>
"""

    # GitHub 설정 확인
    github_configured = GITHUB_USERNAME != "YOUR_GITHUB_USERNAME"

    html = f"""
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>🤖 {SYSTEM_TITLE}</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{
            font-family: 'Segoe UI', -apple-system, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            padding: 20px;
            line-height: 1.6;
        }}
        .container {{
            max-width: 1400px;
            margin: 0 auto;
            background: white;
            border-radius: 20px;
            box-shadow: 0 20px 60px rgba(0,0,0,0.3);
            overflow: hidden;
        }}
        .header {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 40px;
            text-align: center;
        }}
        .header h1 {{
            font-size: 2.5em;
            margin-bottom: 10px;
        }}
        .update-info {{
            font-size: 1.2em;
            margin-top: 15px;
            padding: 15px;
            background: rgba(255,255,255,0.2);
            border-radius: 10px;
            display: inline-block;
        }}
        .update-info .time {{
            font-weight: bold;
            font-size: 1.3em;
        }}
        .update-info .notice {{
            margin-top: 10px;
            font-size: 0.9em;
            opacity: 0.9;
        }}
        .refresh-btn {{
            background: white;
            color: #667eea;
            border: none;
            padding: 15px 40px;
            border-radius: 50px;
            font-size: 1.1em;
            font-weight: bold;
            cursor: pointer;
            margin-top: 20px;
            transition: all 0.3s;
        }}
        .refresh-btn:hover {{
            background: #f0f0f0;
            transform: scale(1.05);
        }}
        .refresh-btn:disabled {{
            opacity: 0.6;
            cursor: not-allowed;
        }}
        #refresh-status {{
            margin-top: 15px;
            font-size: 0.9em;
            display: none;
        }}
        .content {{ padding: 40px; }}

        /* 나머지 스타일은 동일... (생략) */
        .section {{
            margin-bottom: 40px;
            background: #f8f9fa;
            border-radius: 15px;
            padding: 30px;
        }}
        .section-title {{
            font-size: 1.8em;
            color: #2d3748;
            margin-bottom: 20px;
            display: flex;
            align-items: center;
            gap: 10px;
        }}
        .top8-grid {{
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 20px;
        }}
        @media (max-width: 1200px) {{
            .top8-grid {{ grid-template-columns: repeat(2, 1fr); }}
        }}
        @media (max-width: 768px) {{
            .top8-grid {{ grid-template-columns: 1fr; }}
        }}
        .stock-card {{
            background: white;
            border-radius: 12px;
            padding: 20px;
            box-shadow: 0 3px 10px rgba(0,0,0,0.1);
            transition: all 0.3s;
        }}
        .stock-card:hover {{
            transform: translateY(-5px);
            box-shadow: 0 6px 20px rgba(0,0,0,0.15);
        }}
        .stock-rank {{ font-size: 2em; margin-bottom: 10px; }}
        .stock-name {{
            font-size: 1.3em;
            font-weight: bold;
            color: #2d3748;
            margin-bottom: 5px;
        }}
        .stock-price {{
            font-size: 1.5em;
            font-weight: bold;
            color: #667eea;
            margin: 10px 0;
        }}
        .stock-change {{
            font-size: 0.9em;
            padding: 3px 10px;
            border-radius: 12px;
            display: inline-block;
        }}
        .stock-change.up {{ background: #fed7d7; color: #c53030; }}
        .stock-change.down {{ background: #bee3f8; color: #2c5282; }}
        .stock-reasons {{
            margin-top: 15px;
            font-size: 0.9em;
            color: #4a5568;
        }}
        .stock-reasons div {{
            padding: 5px 0;
            border-bottom: 1px solid #e2e8f0;
        }}
        .stock-targets {{
            display: flex;
            justify-content: space-between;
            margin-top: 15px;
            padding-top: 15px;
            border-top: 2px solid #e2e8f0;
        }}
        .target-item {{ text-align: center; }}
        .target-label {{
            font-size: 0.85em;
            color: #718096;
        }}
        .target-value {{
            font-size: 1.1em;
            font-weight: bold;
            margin-top: 3px;
        }}
        .target-value.profit {{ color: #38a169; }}
        .target-value.loss {{ color: #e53e3e; }}
        .target-value.risk-low {{ color: #38a169; }}
        .target-value.risk-mid {{ color: #f59e0b; }}
        .target-value.risk-high {{ color: #e53e3e; }}
        .market-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
            gap: 20px;
        }}
        .market-box {{
            background: white;
            padding: 20px;
            border-radius: 12px;
            text-align: center;
        }}
        .market-label {{
            font-size: 0.9em;
            color: #718096;
            margin-bottom: 10px;
        }}
        .market-value {{
            font-size: 2em;
            font-weight: bold;
            color: #2d3748;
        }}
        .market-change {{
            font-size: 1.1em;
            margin-top: 5px;
        }}
        .signal-tabs {{
            display: flex;
            gap: 10px;
            margin-bottom: 20px;
            flex-wrap: wrap;
        }}
        .signal-tab {{
            padding: 10px 20px;
            background: white;
            border: none;
            border-radius: 8px;
            cursor: pointer;
            font-weight: bold;
            transition: all 0.3s;
        }}
        .signal-tab.active {{
            background: #667eea;
            color: white;
        }}
        .signal-list {{
            background: white;
            border-radius: 12px;
            padding: 20px;
        }}
        .signal-item {{
            display: flex;
            justify-content: space-between;
            padding: 12px;
            border-bottom: 1px solid #e2e8f0;
        }}
        .signal-item:last-child {{ border-bottom: none; }}
        .sector-item {{
            background: white;
            padding: 15px 20px;
            border-radius: 10px;
            margin-bottom: 10px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }}
        .sector-name {{
            font-size: 1.1em;
            font-weight: bold;
            color: #2d3748;
        }}
        .sector-info {{
            display: flex;
            gap: 15px;
            font-size: 0.9em;
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🤖 {SYSTEM_TITLE}</h1>
            <div class="update-info">
                <div class="time">📅 {update_time} ({weekday_kr.get(weekday, weekday)}) 데이터</div>
                <div class="notice">
                    💡 매일 평일 오전 8시 자동 업데이트 (주말 제외)
                </div>
            </div>
            <button class="refresh-btn" onclick="triggerRefresh()" id="refreshBtn">
                🔄 지금 바로 새로 분석하기
            </button>
            <div id="refresh-status"></div>
        </div>
"""

    # 나머지 HTML 생성 (TOP 8 카드, 시장 브리핑 등)
    # ... (이전과 동일한 코드, 너무 길어서 핵심만 포함)

    html += """
        <div class="content">
            <div class="section">
                <div class="section-title">
                    🎯 오늘의 TOP 8 추천 종목
                    <span style="font-size: 0.6em; color: #718096;">(저평가 + 과매도 + VWAP 지지)</span>
                </div>
                <div class="top8-grid">
"""

    medals = ['🥇', '🥈', '🥉', '4️⃣', '5️⃣', '6️⃣', '7️⃣', '8️⃣']
    for idx, stock in enumerate(top8):
        tech = stock['tech']
        risk = stock.get('risk_level', '중')
        change_class = 'up' if tech['change_pct'] > 0 else 'down'
        change_sign = '+' if tech['change_pct'] > 0 else ''
        target_price = int(tech['current_price'] * 1.10)
        stop_loss = int(tech['current_price'] * 0.95)
        risk_class = 'risk-low' if risk == '저' else 'risk-mid' if risk == '중' else 'risk-high'

        html += f"""
                    <div class="stock-card">
                        <div class="stock-rank">{medals[idx]}</div>
                        <div class="stock-name">{tech['name']}</div>
                        <div style="font-size: 0.9em; color: #718096;">({tech['code']})</div>
                        <div class="stock-price">{tech['current_price']:,}원</div>
                        <span class="stock-change {change_class}">{change_sign}{tech['change_pct']}%</span>
                        <div class="stock-reasons"><strong>추천 이유:</strong>
"""
        for reason in stock['reasons'][:3]:
            html += f"<div>✓ {reason}</div>"

        html += f"""
                        </div>
                        <div class="stock-targets">
                            <div class="target-item">
                                <div class="target-label">목표가</div>
                                <div class="target-value profit">{target_price:,}원</div>
                            </div>
                            <div class="target-item">
                                <div class="target-label">손절가</div>
                                <div class="target-value loss">{stop_loss:,}원</div>
                            </div>
                            <div class="target-item">
                                <div class="target-label">위험도</div>
                                <div class="target-value {risk_class}">{risk}</div>
                            </div>
                        </div>
                    </div>
"""

    html += """
                </div>
            </div>
        </div>
    </div>

    <script>
        function showTab(tabName) {
            document.querySelectorAll('.signal-tab').forEach(tab => tab.classList.remove('active'));
            event.target.classList.add('active');
            document.querySelectorAll('.signal-list').forEach(list => list.style.display = 'none');
            document.getElementById('tab-' + tabName).style.display = 'block';
        }

        async function triggerRefresh() {
"""

    if github_configured:
        html += f"""
            const btn = document.getElementById('refreshBtn');
            const status = document.getElementById('refresh-status');

            btn.disabled = true;
            btn.innerHTML = '⏳ GitHub Actions 실행 중...';
            status.style.display = 'block';
            status.style.color = '#667eea';
            status.innerHTML = '🚀 분석 시작! 약 45분 소요됩니다.<br>💡 이 창을 닫아도 백그라운드에서 계속 진행됩니다.';

            try {{
                const response = await fetch('https://api.github.com/repos/{GITHUB_USERNAME}/{GITHUB_REPO}/actions/workflows/final.yml/dispatches', {{
                    method: 'POST',
                    headers: {{
                        'Authorization': 'Bearer {GITHUB_TOKEN}',
                        'Accept': 'application/vnd.github.v3+json',
                        'Content-Type': 'application/json'
                    }},
                    body: JSON.stringify({{
                        ref: 'main'
                    }})
                }});

                if (response.status === 204) {{
                    status.innerHTML = '✅ 분석 시작 성공!<br>📊 45분 후 이 페이지를 새로고침하면 최신 데이터를 볼 수 있습니다.<br>🔗 <a href="https://github.com/{GITHUB_USERNAME}/{GITHUB_REPO}/actions" target="_blank" style="color: white;">진행 상황 확인하기</a>';
                    status.style.color = '#38a169';

                    setTimeout(() => {{
                        btn.disabled = false;
                        btn.innerHTML = '🔄 지금 바로 새로 분석하기';
                    }}, 5000);
                }} else {{
                    throw new Error('API 호출 실패');
                }}
            }} catch (error) {{
                status.innerHTML = '❌ 오류 발생: ' + error.message + '<br>💡 GitHub 설정을 확인하세요.';
                status.style.color = '#e53e3e';
                btn.disabled = false;
                btn.innerHTML = '🔄 지금 바로 새로 분석하기';
            }}
"""
    else:
        html += """
            alert('⚠️ GitHub 설정이 필요합니다!\\n\\n1. GitHub Personal Access Token 생성\\n2. Python 코드에서 GITHUB_USERNAME, GITHUB_REPO, GITHUB_TOKEN 설정\\n\\n자세한 방법은 README 파일을 참고하세요.');
"""

    html += """
        }
    </script>
</body>
</html>
"""

    return html


def main():
    """메인 실행"""
    print("\n" + "="*70)
    print(f"🤖 {SYSTEM_TITLE} v3.1")
    print("="*70)

    analyzer = StockAnalyzer()

    print("\n📊 시장 개요 수집 중...")
    market_data = get_market_overview()

    top8, golden_cross, high_volume, sector_analysis = analyzer.scan_stocks()

    if not top8:
        print("\n❌ 추천 종목을 찾을 수 없습니다.")
        return None

    print(f"\n✅ TOP 8 추천:")
    for idx, stock in enumerate(top8, 1):
        risk = stock.get('risk_level', '중')
        print(f"  {idx}. {stock['tech']['name']} - {stock['tech']['current_price']:,}원 (점수: {stock['score']}, 위험도: {risk})")

    print("\n📝 HTML 리포트 생성 중...")
    html = generate_html(top8, golden_cross, high_volume, sector_analysis, market_data)

    output_file = 'stock_recommendation_final.html'
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(html)

    print(f"✅ 완료: {output_file}")
    print("="*70)

    try:
        from google.colab import files
        files.download(output_file)
    except:
        pass

    return output_file


if __name__ == "__main__":
    main()